#!/usr/bin/env python3
"""Generate docs/posture-register.md from posture.yml.

Why this exists
---------------
Lab environments accumulate weakenings. Each one is defensible when made and
invisible three weeks later. Security Defaults gets disabled to remove an MFA
prompt; device join is opened to All for convenience; a compliance connector is
left off because nothing needed it yet. None of those is a mistake. Forgetting
all of them simultaneously is.

This register is the audit artifact: every security-relevant setting observed,
what it is, why it is that way, and whether it must be reconsidered before the
project is called finished.

Two distinctions carry the weight:

  verified — was this state SEEN, or merely asserted? An unverified entry is a
             claim. The register reports the split rather than blurring it.

  kind     — a `default` was inherited, not chosen. Recording it as a default
             prevents it later reading as a deliberate decision it never was.

Usage:
    python3 scripts/build-posture-register.py           # regenerate
    python3 scripts/build-posture-register.py --check   # CI staleness gate
"""
from __future__ import annotations

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "posture.yml"
OUTPUT = ROOT / "docs" / "posture-register.md"

KIND_LABEL = {
    "hardened": "hardened",
    "default": "default",
    "weakening": "**weakening**",
    "gap": "**gap**",
}


def render(entries: list[dict]) -> str:
    revisit = [e for e in entries if e.get("revisit")]
    unverified = [e for e in entries if not e.get("verified")]
    by_kind: dict[str, int] = {}
    for e in entries:
        by_kind[e.get("kind", "?")] = by_kind.get(e.get("kind", "?"), 0) + 1

    L = [
        "# Security Posture Register",
        "",
        "<!-- GENERATED by scripts/build-posture-register.py from posture.yml — do not edit by hand. -->",
        "",
        "Every security-relevant setting observed in this environment, its state, and",
        "whether it must be reconsidered before the project is complete.",
        "",
        "A lab accumulates weakenings. Each is defensible when made and invisible three",
        "weeks later. This register exists so the final audit is a lookup rather than an",
        "excavation.",
        "",
        "## Legend",
        "",
        "| Kind | Meaning |",
        "|---|---|",
        "| hardened | Set to the secure/recommended value |",
        "| default | Inherited, not chosen — recorded so it is never mistaken for a decision |",
        "| **weakening** | Deliberately loosened for lab convenience; production answer differs |",
        "| **gap** | Should be enabled per vendor guidance or exam scope; currently is not |",
        "",
        "**Verified** means the state was observed directly in a portal view. Unverified",
        "entries are assertions, not findings, and are listed separately below.",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Settings tracked | {len(entries)} |",
        f"| Verified by direct observation | {len(entries) - len(unverified)} |",
        f"| Asserted but unverified | {len(unverified)} |",
        f"| Flagged to revisit | {len(revisit)} |",
        "",
        "| Kind | Count |",
        "|---|---|",
    ]
    for k in ("hardened", "default", "weakening", "gap"):
        if k in by_kind:
            L.append(f"| {KIND_LABEL[k]} | {by_kind[k]} |")

    L += ["", "## Flagged to revisit", ""]
    if not revisit:
        L += ["Nothing outstanding.", ""]
    else:
        L += [
            "These are open until explicitly closed. A weakening left in place at the end",
            "of the project is acceptable **if it is a decision**; it is not acceptable if",
            "it is an oversight. Closing an item means recording which one it was.",
            "",
            "| ID | Lab | Setting | State | Kind | Production answer | Verified |",
            "|---|---|---|---|---|---|---|",
        ]
        for e in revisit:
            L.append(
                f"| `{e['id']}` | {e['lab']} | {e['setting']} | {e['state']} | "
                f"{KIND_LABEL.get(e.get('kind','?'), '?')} | {e.get('production','—')} | "
                f"{e.get('verified') or '**no**'} |"
            )
        L.append("")

    L += ["## All tracked settings", ""]
    for lab in sorted({e["lab"] for e in entries}):
        L += [f"### Lab {lab}", "",
              "| ID | Setting | Location | State | Kind | Revisit | Verified |",
              "|---|---|---|---|---|---|---|"]
        for e in [x for x in entries if x["lab"] == lab]:
            L.append(
                f"| `{e['id']}` | {e['setting']} | `{e.get('location','—')}` | "
                f"{e['state']} | {KIND_LABEL.get(e.get('kind','?'), '?')} | "
                f"{'yes' if e.get('revisit') else 'no'} | "
                f"{e.get('verified') or '**no**'} |"
            )
        L.append("")
        for e in [x for x in entries if x["lab"] == lab and x.get("note")]:
            L += [f"**`{e['id']}` — {e['setting']}.** {' '.join(e['note'].split())}", ""]

    if unverified:
        L += [
            "## Asserted but not observed",
            "",
            "These states are recorded on the operator's word rather than a portal view.",
            "They are the register's weakest entries and the cheapest to fix.",
            "",
            "| ID | Lab | Setting | How to verify |",
            "|---|---|---|---|",
        ]
        for e in unverified:
            L.append(f"| `{e['id']}` | {e['lab']} | {e['setting']} | `{e.get('location','—')}` |")
        L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or {}
    content = render(data.get("entries") or [])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print("Posture register is stale.", file=sys.stderr)
            print("Run: python3 scripts/build-posture-register.py", file=sys.stderr)
            return 1
        print("Posture register up to date.")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
