#!/usr/bin/env python3
"""Generate docs/attack-coverage.md from detection spec frontmatter.

The README advertises an ATT&CK coverage matrix. A hand-maintained matrix
drifts from the detections it claims to describe within about two weeks, so it
is derived instead: the detection specs are the source of truth and this
regenerates the table from them.

Deliberate design point: a detection with `validated: false` is reported as
CLAIMED, not COVERED. The gap between "I wrote a rule" and "I proved it fires"
is the interesting part of a coverage map, and collapsing the two is how
coverage maps end up lying.

Usage:
    python3 scripts/build-attack-matrix.py [--check]

    --check  exit 1 if the committed matrix is stale (for CI)
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DETECTIONS = ROOT / "detections"
OUTPUT = ROOT / "docs" / "attack-coverage.md"

TACTIC_NAMES = {
    "TA0001": "Initial Access", "TA0002": "Execution", "TA0003": "Persistence",
    "TA0004": "Privilege Escalation", "TA0005": "Defense Evasion",
    "TA0006": "Credential Access", "TA0007": "Discovery",
    "TA0008": "Lateral Movement", "TA0009": "Collection",
    "TA0010": "Exfiltration", "TA0011": "Command and Control",
    "TA0040": "Impact", "TA0043": "Reconnaissance",
    "TA0042": "Resource Development",
}


def parse_frontmatter(text: str) -> dict | None:
    """Minimal YAML frontmatter reader.

    Intentionally dependency-free: this runs in a pre-commit hook and in CI,
    and adding PyYAML to make a contributor's first commit fail is a poor
    trade. Handles only the scalar/list subset the template uses.
    """
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return None

    data: dict = {}
    key = None
    for raw in m.group(1).splitlines():
        line = raw.split(" #")[0].rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if re.match(r"^\s+-\s+", line):
            if key:
                data.setdefault(key, []).append(line.split("-", 1)[1].strip())
            continue
        if ":" in line:
            k, v = line.split(":", 1)
            key = k.strip()
            v = v.strip()
            data[key] = v if v else []
    return data


def truthy(v) -> bool:
    return str(v).strip().lower() in {"true", "yes", "1"}


def collect() -> list[dict]:
    specs = []
    for path in sorted(DETECTIONS.rglob("*.md")):
        if path.name.startswith("_") or path.name == "README.md":
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm or not fm.get("id"):
            continue
        if str(fm.get("id")).strip() == "DET-000":  # untouched template copy
            continue
        fm["_path"] = path.relative_to(ROOT).as_posix()
        specs.append(fm)
    return specs


def render(specs: list[dict]) -> str:
    lines = [
        "# ATT&CK Coverage",
        "",
        "<!-- GENERATED by scripts/build-attack-matrix.py — do not edit by hand. -->",
        "",
        "Derived from detection spec frontmatter in `detections/`.",
        "",
        '**COVERED** means every rule mapped to that tactic has been proven to fire',
        "on a known-true event (`validated: true`). **PARTIAL** means some have.",
        "**CLAIMED** means none have. The distinction is the point of this table: an",
        "unvalidated rule is a hypothesis, not coverage.",
        "",
    ]

    if not specs:
        lines += ["*No detections specified yet.*", ""]
        return "\n".join(lines)

    active = [s for s in specs if str(s.get("status")).strip() != "retired"]
    validated = [s for s in active if truthy(s.get("validated"))]

    lines += [
        "## Summary",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Detections specified | {len(specs)} |",
        f"| Active (not retired) | {len(active)} |",
        f"| Validated (proven to fire) | {len(validated)} |",
        f"| Unvalidated | {len(active) - len(validated)} |",
        "",
        "## By Tactic",
        "",
        "| Tactic | Techniques | Detections | State |",
        "|---|---|---|---|",
    ]

    by_tactic: dict[str, list[dict]] = {}
    for s in active:
        for t in s.get("tactics") or ["(unmapped)"]:
            by_tactic.setdefault(str(t).strip(), []).append(s)

    for tactic in sorted(by_tactic):
        rows = by_tactic[tactic]
        name = TACTIC_NAMES.get(tactic, tactic)
        techs = sorted({t for r in rows for t in (r.get("techniques") or [])})
        ids = ", ".join(f"`{r['id']}`" for r in rows)
        n_ok = sum(1 for r in rows if truthy(r.get("validated")))
        if n_ok == 0:
            state = f"CLAIMED (0/{len(rows)})"
        elif n_ok == len(rows):
            state = f"COVERED ({n_ok}/{len(rows)})"
        else:
            # Partial must never render as COVERED. A single validated rule does
            # not make a tactic green when its sibling techniques are unproven —
            # that is exactly the overstatement this table exists to prevent.
            state = f"PARTIAL ({n_ok}/{len(rows)})"
        lines.append(
            f"| {name} (`{tactic}`) | {', '.join(techs) or '—'} | {ids} | {state} |"
        )

    lines += ["", "## Detections", "",
              "| ID | Name | Platform | Type | Severity | Status | Validated |",
              "|---|---|---|---|---|---|---|"]
    for s in sorted(specs, key=lambda x: str(x["id"])):
        lines.append(
            f"| [`{s['id']}`]({s['_path']}) | {s.get('name','')} | "
            f"{s.get('platform','')} | {s.get('rule_type','')} | "
            f"{s.get('severity','')} | {s.get('status','')} | "
            f"{'yes' if truthy(s.get('validated')) else '**no**'} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if committed matrix is stale")
    args = ap.parse_args()

    content = render(collect())
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print("ATT&CK coverage matrix is stale.", file=sys.stderr)
            print("Run: python3 scripts/build-attack-matrix.py", file=sys.stderr)
            return 1
        print("ATT&CK coverage matrix up to date.")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
