#!/usr/bin/env python3
"""Generate docs/lessons-index.md from lessons/MOD-*.md frontmatter.

Why this exists
---------------
This repository is indexed by **lab** — a lab is a thing that was built. The
course is indexed by **module**, and the two do not line up. Module 52 produced
Lab 09. Modules 53, 54 and 55 produced no lab at all: their findings landed as
amendments to Labs 03, 06 and 09, as posture entries, and as divergence rows.

So a question with an obvious answer — "what did module 54 teach?" — had no
place to be answered. `lessons/` is that place. It is a narrative layer indexed
by module, and it **cross-references rather than restates**: a finding lives in
exactly one authoritative file, and the lesson points at it.

That constraint is the whole design. Two homes for one finding is two things
that drift, and the repository already carries one instance of that failure
(`POS-022` reached the register and never reached its lab — see
`check-lab-coverage.py`).

What it checks
--------------
1. **Staleness** — the index matches the frontmatter it was generated from.
2. **Referential integrity** — every `POS-xxx` a lesson cites actually exists in
   `posture.yml`, and every lab it cites exists on disk.

The second is the useful one. A lesson naming `POS-999` or Lab 47 is a citation
to nothing, and prose is exactly where that rots unnoticed. This is the same
class of check as the lab-coverage gate, approached from the other end: that
one asks whether the register reached the writeups, this one asks whether the
writeups point at a register that exists.

It does NOT check that the lesson's characterisation is accurate. Nothing
mechanical can. Citation is not comprehension.

Usage:
    python3 scripts/build-lessons-index.py            # regenerate
    python3 scripts/build-lessons-index.py --check    # CI: staleness + integrity
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

ROOT = pathlib.Path(__file__).resolve().parent.parent
LESSONS = ROOT / "lessons"
POSTURE = ROOT / "posture.yml"
LABS = ROOT / "labs"
OUTPUT = ROOT / "docs" / "lessons-index.md"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)

VERDICT_LABEL = {
    "lab": "🔨 lab",
    "concept": "📖 concept",
    "mixed": "🔀 mixed",
}


def load() -> list[dict]:
    out = []
    for path in sorted(LESSONS.glob("MOD-*.md")):
        text = path.read_text(encoding="utf-8")
        m = FRONTMATTER.match(text)
        if not m:
            print(f"WARN {path.name}: no frontmatter, skipped", file=sys.stderr)
            continue
        meta = yaml.safe_load(m.group(1)) or {}
        meta["_path"] = path.relative_to(ROOT).as_posix()
        meta["_name"] = path.name
        out.append(meta)
    return sorted(out, key=lambda m: int(m.get("module", 0)))


def integrity(entries: list[dict]) -> list[str]:
    """Every cited POS-xxx and lab must exist. Returns error strings."""
    data = yaml.safe_load(POSTURE.read_text(encoding="utf-8")) or {}
    known_pos = {e["id"] for e in (data.get("entries") or [])}
    known_labs = {d.name.split("-")[0] for d in LABS.iterdir() if d.is_dir()}

    errors = []
    for e in entries:
        arts = e.get("artifacts") or {}
        for pid in arts.get("posture") or []:
            if pid not in known_pos:
                errors.append(f"{e['_name']}: cites {pid}, which is not in posture.yml")
        for lab in arts.get("labs") or []:
            if str(lab) not in known_labs:
                errors.append(f"{e['_name']}: cites lab {lab}, which does not exist")
    return errors


def render(entries: list[dict]) -> str:
    labs = sum(1 for e in entries if e.get("verdict") == "lab")
    corrections = sum(len(e.get("corrections") or []) for e in entries)

    L = [
        "# Module Lessons — Index",
        "",
        "<!-- GENERATED by scripts/build-lessons-index.py — do not edit by hand. -->",
        "",
        "This repository is indexed by **lab**; the course is indexed by **module**,",
        "and the two do not line up. Most modules produce no lab — their findings land",
        "as amendments to existing labs, as posture entries, and as divergence rows.",
        "`lessons/` answers the module-shaped question, and **cross-references rather",
        "than restates**: each finding has exactly one authoritative home.",
        "",
        f"**{len(entries)} module(s) recorded · {labs} produced a lab · "
        f"{corrections} correction(s) to previously committed content.**",
        "",
        "| Module | Title | Verdict | Labs | Posture | Divergences | Corrections |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        a = e.get("artifacts") or {}
        f = lambda xs, p="": ", ".join(f"`{p}{x}`" for x in xs) if xs else "—"
        L.append(
            f"| [{e.get('module')}]({pathlib.Path('..') / e['_path']}) "
            f"| {e.get('title','—')} "
            f"| {VERDICT_LABEL.get(e.get('verdict'), e.get('verdict','—'))} "
            f"| {f(a.get('labs') or [], 'Lab ')} "
            f"| {f(a.get('posture') or [])} "
            f"| {f(a.get('divergences') or [], 'row ')} "
            f"| {len(e.get('corrections') or []) or '—'} |"
        )

    corr = [(e, c) for e in entries for c in (e.get("corrections") or [])]
    if corr:
        L += [
            "",
            "## Corrections to previously committed content",
            "",
            "Claims that shipped and were later killed by measurement. Kept visible",
            "because a repository that only records its successes is not evidence of",
            "anything.",
            "",
            "| Module | What was corrected |",
            "|---|---|",
        ]
        for e, c in corr:
            L.append(f"| {e.get('module')} | {c} |")

    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="CI: staleness + integrity")
    args = ap.parse_args()

    if not LESSONS.exists():
        print("No lessons/ directory; nothing to do.")
        return 0

    entries = load()
    errors = integrity(entries)
    content = render(entries)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print("Lessons index is stale.", file=sys.stderr)
            print("Run: python3 scripts/build-lessons-index.py", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")

    if errors:
        for e in errors:
            print(f"FAIL {e}", file=sys.stderr)
        print(
            "\nA lesson citing a handle that does not exist is a citation to nothing.",
            file=sys.stderr,
        )
        return 1

    if args.check:
        print(f"Lessons index up to date; {len(entries)} module(s), all citations resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
